language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dibisis
  password:
    secure: "oONHrl8TPWJJrGvuDBU1naryteskWk69JIP+BMFD9frwdil/jvc/0UpjFIhDEDGZdafAloPODE7R7UFGoEDvA44VLK9piQVqqYf+WHHKll8Mave+G3mduImKzwRKWU7YcYOv0F3HCpJbXPy2YRn64FD1WXqMAZjiMDLNO7iantNLQepFUce5XSVbJofVoZPw/7/xu0VS5fL7wFKgW5LTBBzqqJmdTZMdedGKzd3EqVP7B/N5A5QbkU1BPejEVxE6fdUt8Y9zJHHNdaVw3f07iAn/JSku3+QRUwyca4w96RCgrWDYZiNEyXSZw8tr92yOS5FotX4wKuKNQruPkt0yHHvGgZy4RhY6oN83uQ/vFijQaeVtk/Mbm7MTOcWyCXWI6aHeUOLksmcyFVuRZGfopK32yArsui26ByhB7cLOJ2JHYxPlGlSTxc+OWtX94GDS0kNQuF/ikmAWe9ywZDFK3OQ1fQrmyHBP0pi8lyTac//5pnRHMbDbLAnoDT9Si1q4M7B6ZUfh0ZxLBmjwqyObze/Y1sv5Cr0nh7ahlUCSmefFLSlcKJMCN8KHwc1fPeHoirdJKEPC6ffjllW3kplrFDoOf65J/ka7gIBOW0LHKf93mlgy4GENn4a/jJZZ6j/jIrPcTWzwGZSCFTO8OVjM/3WLuB+IbnXNCoOW52XRy54="
  on:
    tags: true
    repo: dibisis/checking_smtp_starttls
    python: 3.6
