language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dibisis
  password:
    secure: tBkH/B8tI5y+g/NtQrj1J37WZTUF57YNOxCYMtt8mWMwxW60zlIERc6dYS00E54DMpQ4eedcfdm+XpmWh0jlwttnj94j/tvPAnu1Weufz4NiCG93WQ28LZ2GXbzk+s+2ops3LJdwQVlzHLuz+rA22K55T4G9Mb13hP145jgOFSH8F4pqiXrhYOUFP26ScHZGtRgRpLtOtLmJkty1BrWrMbbkSM2t1+lQwXGggtO8x3MRfI/GDACTyShmC2kzRPlTS8FpmwqldjtTgcZRCDQeT2ZYBODaKBNNqlFD/xQwIOT8sq1g0X0+KZkP0RiwPvMX4Db+8kUZpWn88d/kGB2ifUxPg+SKk+1jsZdqihk379z0bIdh95kcT2urqZ5UArVUNZLnELoWQOhoKudqhyq3PAIzuqOH2G+xf6s2EHf06sXiAColpgqKzaVlEvMBYkHUyHWjF4XMwZzURtHX0Nn3ziAcv9nCOegtD6gcXdDF4BV1cZB7JHS8rLryLtrCh7bu8uWZQXH9RYI5DYcHq36srt1zuKRmeyqxrrnNWUfdQcw+N54URQ9H00QcxSqqmyqizrUePHZbSiWgqEy3zDFpop/lRvf0EUJq/QrZ37XqFU08ZpsX8hHDKjUqAOLNUAiYhny4LE6iOwc9BCDVMbJNfnmVYq7JcbJ9HnzdbX2Jldg=
  on:
    tags: true
    repo: dibisis/checking_smtp_starttls
    python: 3.6
