language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dibisis
  password:
    secure: FqMPgy2q6MdEGHRW8ViNMAyfzt9kGxW0WPyNdIRXLf6qW7q4twP0f+F598bTMifFeM2n011PaNSZ8QLlLBuFezA4pZTq7048momMsATzR2JdAfgrTh5jDJF1Zl3fqDW+z4LmGFq3Supv/LyUrVDf5GDfTYgN3GsvAmrURqZaGEqduQzG2YNJXTUcg8kYLQ0xAsdkE9cPmJpOKXRNF4nh09NY2Sz1ASaBUNdPeREVbkzQNVZS2ZubD/hE9e2UIyak7t+kHy8+Cca/SYWJyngD3XKym/H0pLnhQxaITRIhnzyZZjsow7RFsdLHUBK36cEValB30CLjIfwoc7kq3tNW2qDdr/0N5hws5ofvjDsseUv9Z42BC/7r5WA0b8gv3IpAA2OHvL3CXOYkraA6bOCQHL85tLF7cvRQYFbLWZHPVIESEh+Xs+2Ui5bzoxa/EqaspXIXp78XOhtzGk3KihVZjmVsbb7yHtw+CoSZGJuYKFZ1tjqNYKY47u7OOPYJE4BSbVb/OtqmGkXABQHlm9Kx6un+XRDNSxj3GV8/oXMjPGDkYcd2VVcTf3aUOuYhZDP6gavRL9wtbaq2X/hd5BMdcM+MIxKIH0YJ5nfSuDI3VKWt5Rum6Q1JCVE0xxiVY3ZAZvyWx0AE5A1N4vIYDBqH6eI63M3IsFAI/dvQ8NvuZmY=
  on:
    tags: true
    repo: dibisis/checking_smtp_starttls
    python: 3.6
