language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dibisis
  password:
    secure: UMfzRVXS/EsVW0OXC3EPwB6pxYVt4c7XPeIhZ8mOz5ejeegERNINKMz+YT+uHY9DodvvXEuDtvvflag+yFZZS3I73EudLlBSVOARGH7nU1Y99IotHYL48U7IPJnCYDAFYpNJcTN55m3yQh+t1tk+NNmwwht7gNPh+1/Q8Aahqjucp26jWMlPPnvEE9ONL1Pl/P7ges9sbfOQYp+qjwXyh9O4cFvsGt7NcczJHXiOe+qh50MU979oudv/DNY3ZtsB7JABq3EKu5pR0ITYzlBWMX8g+SP79fNxGJg4L5tyF0WWtBBAZGBmFFDNf8PWzOv3QVMSs8QKxNVNRFmCopD/sIimCzoq0BL/C+dwmI2ayLSNkwVBZrPy9k+aaFdpgit4qrdssB1Y1QZtiv9JCkea9+lVtl3WVgdvsKo9unN9spLpS6gkPVyUoEzydWdlabQ/O+nE+1L7UIVRFAQNueyEe9V4kP+ml6qzo7wfm6m/J6ExKs8L08AWnpVaeTu1u1jXxPDqoyKxIJRSmkFAoNC7YDRfzyCQC077gpdTRVRlGV6ftpKD11hiY0TuyuwC4GmoVvwYTYWXtOtY2ydSuebX2h4w8cn6DpRlC+DwCUq4WvyTBJRTB+mUSPeAjlc72TqjbE1k+3s/C+mM4EazJddYEHQk5ZHnnAotkD72I32Z/T4=
  on:
    tags: true
    repo: dibisis/checking_smtp_starttls
    python: 3.6
