language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dibisis
  password:
    secure: oBKHXE9JJuwrbeznOj7ZQCTAaG5Lyqg0pTI3QeUbNhu4f7RNCcyoKn51jHgInsIeLipUhC1lPN0arhKoiKYZLWp6nBOUHiB3k57C49jk9wydj3CkaRQ3g59nohFRuy7USNtatOa+V2uqOOD37z+md9MeSBYpjqakw+F6vB6yHXQ068LoUDhzkAefH7mpoKmKZmb4UIJZ9oKk/mDY+ltHOqYlF/9Em6spSt5voCmjU9AKv5KS7SB2lrlDN8btG/Xf1HwhAWrAPa+MkyXH0q2SQvphphXZaevWU359i1o1B+h0CwSJ2N6DJ7P9/RdF0+ay82g+Cu7w2SdiRURbzfvD/SKg4euNYg2eAnXCesRQ1GWGhJCTu0tyLb/PXXWI6P/3cT3QJ++sfyJ1NswAixMr+DzVhKPIH1JIvU+zQR70JlasHERKmzQii+M6px8hEEfeA7USaXverhdOw8YstHxn7afKY4a0UBuJXKzQteDm4kp1nqOa1igpN8RigdXv8ghNSIO4cVDLFzx1xaphe6taUaklxDBIKxt5VSOnJKiJdxVNYzFr0TDkC6brtX8IA51cUCmwzkRADpE5XjQDy2oeLRTtKXrnB+3QAuMGh8kkSoYHxcuDcQr0Q1Udj6ujt7A+HVWJRbHMvK/doN4uGzwCdsWEldwjCca56qbb9mUpzlI=
  on:
    tags: true
    repo: dibisis/checking_smtp_starttls
    python: 3.6
