language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dibisis
  password:
    secure: vTeLVql4JCLijPXRoix0+Qep4X9aduCDyYfbxrHq6stG1AUNeV76JoUdPJJOMYXJhMow6zaxV9eRcIFkoC38IAQVtDxyosOU5rzs+8/++/woVduZih/MT+AviTerxOY6jgIQzFItfaqmE2//ebxnDj6vsmRrsEz+xbAjlvS37z3soXQNQ3WF1ieQhQG6f8GzZ3zsuZsE5nrDErivoJBojIFPduPPhB82qPdakZtpNLcI0S1ws2J0r9Bbud11mFsyX99D5sP3g5iBhu/EByD9wcViw3XP3nOJNCByfRPh9WnIv7NNy98tCCoV1SmFvpsa8HciuvX5Mh4YDKAPqxlg2ZuptfQ2W/bZw1VZUSr7blHgSnpC5ypNkcP8hNjWFaY6VUYYUkphI6C2/Yg10jftStLZgGkKqGmJlywuU/vX+tUiC1aW8SFu5QQz6n/yZPYUUHX5Cf1ho1UDAqy1hctLjjzJFZjN3W1GZwVM+Qf9sGshLN7lEy4XYFhJ9JTJFVuFTRiySNM+Ya6kVk7+qiditcVBoE0lRLN9RYVH5GgcyivOpYQ2qYGx0cfVuvdEu53a8wlqyAD/ZRCXayNvMZZo8Bbteyny6vxyf1o/koAcKukEOJOP/g1Ht3B2M+4y8agApdu6GqeQ92BmHGnrDowuexWyeQtsgISMmz8lDx/sZqY=
  on:
    tags: true
    repo: dibisis/checking_smtp_starttls
    python: 3.6
